# Generated by Django 6.0.4 on 2026-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantprofile',
            options={'verbose_name': 'Профиль соискателя', 'verbose_name_plural': 'Профили соискателей'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'verbose_name': 'Профиль работодателя', 'verbose_name_plural': 'Профили работодателей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Файл резюме (байты)'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла резюме'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume_text',
            field=models.TextField(blank=True, verbose_name='Текст резюме'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Степень/квалификация'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(verbose_name='Год начала'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Соискатель'), ('employer', 'Работодатель')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущее место работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
