# Generated by Django 6.0.4 on 2026-04-23 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от (₽)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до (₽)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='Запрос')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-created_at'],
            },
        ),
    ]
